apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homelab-ingress
  namespace: homelab
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod" # Связываем с Issuer
    nginx.ingress.kubernetes.io/ssl-redirect: "true"   # Авто-редирект с http на https
spec:
  ingressClassName: public # Указываем MicroK8s использовать встроенный Nginx
  tls:
  - hosts:
    - memos.nr64.art
    secretName: memos-tls-cert
  - hosts:
    - whoami.nr64.art
    secretName: whoami-tls-cert
  - hosts:
    - ghost.nr64.art
    secretName: ghost-tls-cert
  rules:
  - host: memos.nr64.art
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: memos-service
            port:
              number: 5230
  - host: whoami.nr64.art
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: whoami-service
            port:
              number: 5231
  - host: ghost.nr64.art
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ghost-service
            port:
              number: 80
